Q 8: Write a NumPy program to create an array of all the even integers from 30 to 70

In [6]:
import numpy as np

In [7]:
even_arr = np.array(range(30, 71, 2))

In [8]:
even_arr

array([30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62,
       64, 66, 68, 70])

Q 9: Write a NumPy program to compute sum of all elements, sum of
each column and sum of each row of a given array

In [11]:
arr1 = np.random.randint(1, 30, 9).reshape(3, 3)
arr1

array([[ 3, 26,  8],
       [ 6,  4,  7],
       [ 3,  9,  3]])

In [13]:
# Sum of each row 
np.sum(arr1, axis = 0)

array([12, 39, 18])

In [14]:
# Sum of each Column 
np.sum(arr1, axis=1)

array([37, 17, 15])

Q 10: Write a NumPy program to create a 5x5 zero matrix with
elements on the main diagonal equal to 1, 2, 3, 4, 5

In [18]:
zero = np.zeros((5,5))

In [19]:
zero

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [20]:
for i in range(5):
    zero[i, i] = i + 1

In [21]:
zero

array([[1., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0.],
       [0., 0., 3., 0., 0.],
       [0., 0., 0., 4., 0.],
       [0., 0., 0., 0., 5.]])

Q 11: Write a NumPy program to sort a given array by row and column in ascending order

In [22]:
arr2 = np.random.randint(-10, 30, 36).reshape(3, 3, 4)
arr2

array([[[ 19,  -9,  21,   1],
        [-10,  21,  27,   4],
        [ -6,  27,  27,  15]],

       [[  9,   1,  22,  -7],
        [  2,  -9,   6,  -9],
        [ 10,  18,  10,  13]],

       [[ 21,  19,   9,  -5],
        [ 25,   0,  -1,   3],
        [ 25,  18,  -9,  16]]])

In [23]:
arr2.sort()

In [24]:
arr2

array([[[ -9,   1,  19,  21],
        [-10,   4,  21,  27],
        [ -6,  15,  27,  27]],

       [[ -7,   1,   9,  22],
        [ -9,  -9,   2,   6],
        [ 10,  10,  13,  18]],

       [[ -5,   9,  19,  21],
        [ -1,   0,   3,  25],
        [ -9,  16,  18,  25]]])

In [25]:
# Sorting arr2 by column vise
np.sort(arr2, axis=1)

array([[[-10,   1,  19,  21],
        [ -9,   4,  21,  27],
        [ -6,  15,  27,  27]],

       [[ -9,  -9,   2,   6],
        [ -7,   1,   9,  18],
        [ 10,  10,  13,  22]],

       [[ -9,   0,   3,  21],
        [ -5,   9,  18,  25],
        [ -1,  16,  19,  25]]])

Q 12: Write a NumPy program to create a three-dimension array with shape (3,5,4) and set to a variable

In [26]:
arr3 = np.random.randint(1, 100, 64).reshape(4, 4, 4)
arr3

array([[[98, 12, 33, 21],
        [25, 63, 61,  1],
        [ 4, 89, 20, 49],
        [97, 69, 40, 92]],

       [[ 7, 68, 67, 39],
        [ 1, 22, 55, 56],
        [59, 63, 38, 17],
        [48, 47, 39, 85]],

       [[27, 42, 78, 82],
        [42, 52, 16, 97],
        [35, 81, 57, 13],
        [ 9,  6, 81, 75]],

       [[66, 68, 18, 54],
        [67, 16, 98, 47],
        [37, 17, 26, 75],
        [75, 48, 60, 17]]])