Q 13: (a) Write a NumPy program to swap rows and columns of a given array in reverse order. 

In [1]:
import numpy as np

In [3]:
a = np.random.randint(2, 30, 8).reshape(2, 4)

In [4]:
a

array([[25,  2,  5, 10],
       [18, 20, 20,  7]])

In [5]:
a.sort()

In [6]:
a

array([[ 2,  5, 10, 25],
       [ 7, 18, 20, 20]])

(b) Write a NumPy program to multiply two given arrays of same size element-by-element.

In [7]:
arr1 = np.random.randint(2, 40, 9).reshape(3, 3)
arr1

array([[ 9, 26,  2],
       [ 2,  9, 38],
       [25, 27, 24]])

In [8]:
arr2 = np.random.randint(2, 40, 9).reshape(3, 3)
arr2

array([[34, 13, 32],
       [12, 36, 17],
       [23, 39, 39]])

In [10]:
np.multiply(arr1, arr2)

array([[ 306,  338,   64],
       [  24,  324,  646],
       [ 575, 1053,  936]])

Q 14 : Write a NumPy program to print the NumPy version in your system.

In [11]:
np.__version__

'1.24.1'

Q 15: Print max from axis 0 and min from axis 1 from the following 2-D array.

In [17]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])

In [23]:
print("Printing max from axis 0 : \n",np.max(sampleArray, axis=0))# Max from axis 0

Printing max from axis 0 : 
 [82 94 73]


In [21]:
print("Printing min from axis 1 : \n", np.min(sampleArray, axis = 1)) # Min from axis 1

Printing min from axis 1 : 
 [34 12 53]


Q 16: Delete the second column from a given array and insert the following new column in its place
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]])
newColumn = numpy.array([[10,10,10]])

In [24]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
newColumn = np.array([[10,10,10]])

In [33]:
# del sampleArray[0, 1]

In [40]:
a = []
for i in range(len(sampleArray)):
    for j in range(len(sampleArray)):
        if j != 1:
            a.append(sampleArray[i, j])

In [41]:
a

[34, 73, 82, 12, 53, 66]

In [42]:
newArray = np.array(a).reshape(3, 2)

In [46]:
print("Printing Original Array : \n", sampleArray)

Printing Original Array : 
 [[34 43 73]
 [82 22 12]
 [53 94 66]]


In [47]:
print("Array after deleting column 2 on axis 1 : \n", newArray)

Array after deleting column 2 on axis 1 : 
 [[34 73]
 [82 12]
 [53 66]]
